; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560_refactored]
platform = atmelavr
board = megaatmega2560
framework = arduino
test_build_src = yes
monitor_speed = 115200

build_flags =
  -DSTARTRACK_ENABLE_REFACTORED_ARCH

build_src_filter =
  +<main_refactored.cpp>
  +<refactored/*>
  -<main.cpp>
  -<motors.cpp>
  -<switchs.cpp>
